---
title: "ggplot2 themes and palettes"
output: 
  rmarkdown::html_vignette:
    css: uikit.css
    toc: true
vignette: >
  %\VignetteIndexEntry{aa-ggplot2-themes-and-palettes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 7,
  fig.align = "center"
)
# devtools::load_all()
# Copy css from inst
file.copy(system.file("css/uikit.css", package = "drealthemes"), "uikit.css")
```

## Packages
```{r setup}
library(drealthemes)
library(ggplot2)
library(dplyr)
```

# Palettes
```{r}
# Dreal corporate colors
# Created in "data-raw" 
primary <- c("primary_active" = "#00465a", "primary" = "#008ca0", "primary_light" = "#00bebe")
secondary <- c("secondary_active" = "#3c0064", "secondary" = "#5a1e82", "secondary_light" = "#8246aa")
info <- c("info_active" = "#a0a0a0", "info" = "#b4b4b4", "info_light" = "#d2d2d2")
success <- c("success_active" = "#a0c83c", "success" = "#b4dc50", "success_light" = "#c8f064")
warning <- c("warning_active" = "#f59600", "warning" = "#ffd200", "warning_light" = "#fff000")
danger <- c("danger_active" = "#b4003c", "danger" = "#eb3273", "danger_light" = "#ff6e9b")

dreal_colors <- c(secondary, primary, warning, danger, success, info)[
  c(seq(1, 3*6, 3), seq(2, 3*6, 3), seq(3, 3*6, 3))]

# show palette
tibble(
  x = rep(1:3, each = 6),
  y = rep(1:6, times = 3),
  names = names(dreal_colors), 
  colors = dreal_colors) %>% 
  ggplot() +
  aes(x, y, fill = names) +
  geom_tile() +
  geom_text(aes(label = names)) +
  scale_fill_manual(values = dreal_colors) +
  guides(fill = FALSE) +
  theme_void()
```

# Functions
```{r}
#' Function to extract dreal colors as hex codes
#'
#' @param ... Character names of dreal_colors 
#'
#' @examples
#' dreal_cols("primary", "danger")
dreal_cols <- function(...) {
  cols <- c(...)

  if (is.null(cols))
    return(dreal_colors)

  dreal_colors[cols]
}
```

